# config file for testing
# filename should be application.yml

app:
  project: examples-swagger
  name: simple-server
  profiles:
    include:
      - logging
      - swagger
      - actuator

logging:
  level: info
